var photoPosts = [

    {
        id: '1',
        description: '“The gladdest moment in human life, me thinks, is a departure into unknown lands.” – Sir Richard Burton',
        createdAt: new Date('2018-02-23T23:00:00'),
        author: 'Evangelina',
        authorPhoto: 'personalPhotos/personalPhoto2.jpg',
        photoLink: 'posts/post1.jpg',
        hashTags: ['world'],
        likes: [],
    },

    {
        id: '2',
        description: '“Travel makes one modest. You see what a tiny place you occupy in the world.” -Gustav Flaubert',
        createdAt: new Date('2017-02-23T23:00:00'),
        author: 'Catherine',
        authorPhoto: 'personalPhotos/personalPhoto1.jpg',
        photoLink: 'posts/post2.jpg',
        hashTags: ['around', 'travel', 'world'],
        likes: [],
    },

    {
        id: '3',
        description: '“Better to see something once than hear about it a thousand times”',
        createdAt: new Date('2018-02-23T23:00:00'),
        author: 'Catherine',
        authorPhoto: 'personalPhotos/personalPhoto1.jpg',
        photoLink: 'posts/post3.jpg',
        hashTags: ['travel', 'world'],
        likes: [],
    },

    {
        id: '4',
        description: '“To Travel is to Live” – Hans Christian Andersen',
        createdAt: new Date('2018-02-22T23:00:00'),
        author: 'Elizabeth',
        authorPhoto: 'personalPhotos/personalPhoto3.jpg',
        photoLink: 'posts/post4.jpg',
        hashTags: ['travel', 'world'],
        likes: [],
    },

    {
        id: '5',
        description: '“The most beautiful in the world is, of course, the world itself.” -Wallace Stevens',
        createdAt: new Date('2018-02-22T23:00:00'),
        author: 'Evangelina',
        authorPhoto: 'personalPhotos/personalPhoto2.jpg',
        photoLink: 'posts/post5.jpg',
        hashTags: ['world'],
        likes: [],
    },

    {
        id: '6',
        description: '“The journey not the arrival matters.” –T.S. Eliot',
        createdAt: new Date('2018-02-21T23:00:00'),
        author: 'Catherine',
        authorPhoto: 'personalPhotos/personalPhoto1.jpg',
        photoLink: 'posts/post6.jpg',
        hashTags: ['travel', 'world'],
        likes: [],
    },

    {
        id: '7',
        description: '“Dare to live the life you’ve always wanted.”',
        createdAt: new Date('2018-02-21T23:00:00'),
        author: 'Elizabeth',
        authorPhoto: 'personalPhotos/personalPhoto3.jpg',
        photoLink: 'posts/post7.jpg',
        hashTags: ['travel'],
        likes: [],
    },

    {
        id: '8',
        description: '“We live in a wonderful world that is full of beauty, charm, and adventure. There is no end to the adventures we can have if only we seek them with our eyes open.” – Jawaharial Nehru',
        createdAt: new Date('2018-02-21T23:00:00'),
        author: 'Evangelina',
        authorPhoto: 'personalPhotos/personalPhoto2.jpg',
        photoLink: 'posts/post8.jpg',
        hashTags: ['travel', 'world'],
        likes: [],
    },

    {
        id: '9',
        description: '“Don’t listen to what they say. Go see.”',
        createdAt: new Date('2018-02-21T23:00:00'),
        author: 'Elizabeth',
        authorPhoto: 'personalPhotos/personalPhoto3.jpg',
        photoLink: 'posts/post9.jpg',
        hashTags: ['travel'],
        likes: [],
    },

    {
        id: '10',
        description: '“And then there is the most dangerous risk of all — the risk of spending your life not doing what you want on the bet you can buy yourself the freedom to do it later.” – Randy Komisar',
        createdAt: new Date('2018-01-23T23:00:00'),
        author: 'Elizabeth',
        authorPhoto: 'personalPhotos/personalPhoto3.jpg',
        photoLink: 'posts/post10.jpg',
        hashTags: ['world'],
        likes: [],
    },

    {
        id: '11',
        description: '“Life is either a daring adventure or nothing at all.” -Helen Keller',
        createdAt: new Date('2018-01-23T23:00:00'),
        author: 'Catherine',
        authorPhoto: 'personalPhotos/personalPhoto1.jpg',
        photoLink: 'posts/post11.jpg',
        hashTags: ['travel', 'world'],
        likes: [],
    },

    {
        id: '12',
        description: '“One’s destination is never a place, but a new way of seeing things.” -Henry Miller',
        createdAt: new Date('2018-01-23T23:00:00'),
        author: 'Catherine',
        authorPhoto: 'personalPhotos/personalPhoto1.jpg',
        photoLink: 'posts/post12.jpg',
        hashTags: ['travel', 'world'],
        likes: [],
    },

    {
        id: '13',
        description: '“Go, fly, roam, travel, voyage, explore, journey, discover, adventure.”',
        createdAt: new Date('2018-01-01T23:00:00'),
        author: 'Elizabeth',
        authorPhoto: 'personalPhotos/personalPhoto3.jpg',
        photoLink: 'posts/post13.jpg',
        hashTags: ['travel', 'world'],
        likes: [],
    },

    {
        id: '14',
        description: '“All journeys have secret destinations of which the traveler is unaware.” -Martin Buber',
        createdAt: new Date('2018-01-01T23:00:00'),
        author: 'Catherine',
        authorPhoto: 'personalPhotos/personalPhoto1.jpg',
        photoLink: 'posts/post14.jpg',
        hashTags: ['travel', 'world'],
        likes: [],
    },

    {
        id: '15',
        description: '”Travel makes a wise man better but a fool worse.” – Thomas Fuller',
        createdAt: new Date('2017-02-23T23:00:00'),
        author: 'Catherine',
        authorPhoto: 'personalPhotos/personalPhoto1.jpg',
        photoLink: 'posts/post15.jpg',
        hashTags: ['travel', 'world'],
        likes: [],
    },

    {
        id: '16',
        description: '“The world is a book and those who do not travel read only one page.” -Agustine of Hippo',
        createdAt: new Date('2017-02-23T23:00:00'),
        author: 'Elizabeth',
        authorPhoto: 'personalPhotos/personalPhoto3.jpg',
        photoLink: 'posts/post16.jpg',
        hashTags: ['travel', 'world'],
        likes: [],
    },

    {
        id: '17',
        description: '“Not all those who wander are lost.” -J.R.R. Tolkien',
        createdAt: new Date('2017-02-23T23:00:00'),
        author: 'Evangelina',
        authorPhoto: 'personalPhotos/personalPhoto2.jpg',
        photoLink: 'posts/post17.jpg',
        hashTags: ['travel', 'world'],
        likes: [],
    },

    {
        id: '18',
        description: '“Life is short and the world is wide”',
        createdAt: new Date('2017-02-23T23:00:00'),
        author: 'Elizabeth',
        authorPhoto: 'personalPhotos/personalPhoto3.jpg',
        photoLink: 'posts/post18.jpg',
        hashTags: ['travel', 'world'],
        likes: [],
    },

    {
        id: '19',
        description: 'Ж“We travel, some of us forever, to seek other states, other lives, other souls.”-Anaïs Nin',
        createdAt: new Date('2017-02-23T23:00:00'),
        author: 'Catherine',
        authorPhoto: 'personalPhotos/personalPhoto1.jpg',
        photoLink: 'posts/post19.jpg',
        hashTags: ['travel', 'world'],
        likes: [],
    },

    {
        id: '20',
        description: '“Life is a journey. Make the best of it.”',
        createdAt: new Date('2017-02-23T23:00:00'),
        author: 'Evangelina',
        authorPhoto: 'personalPhotos/personalPhoto2.jpg',
        photoLink: 'posts/post20.jpg',
        hashTags: ['travel', 'world'],
        likes: [],
    },
];